### ISSUE TITLE
Mac OSX下MAVEN生成javadoc报错

### ISSUE THREAD

**Issue by chingov** [yizzuide/Milkomeda#2]
### **执行环境**

- Java版本：1.8.0_171
- 系统版本：macOS High Sierra 10.14.6
- Maven版本：3.2.5
- IDE 版本：IDEA 2018.1.2

### **报错说明**

在Mac OSX系统中使用IDEA编译器执行项目的 mvn install 命令，报如下错误：

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project infra-sofa-boot-starter: MavenReportException: Error while creating archive: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]

### **问题研究**

去网上查询解决方法，发现大多和 maven-javadoc-plugin 2.9.x 版本相关，猜测可能是该插件 2.9.x 版本存在的bug。

尝试了以下解决方案，都不再报错：
> 升级 maven-javadoc-plugin 版本到 2.10.1 及以上。

### **建议说明**

建议 milkomeda-spring-boot-starter 升级 maven-javadoc-plugin 插件的版本。

**Comment by yizzuide** [comment]
好的，感谢你的建议

**Comment by yizzuide** [comment]
@chingov 1.12.0主版本已修复
